# Use an official base image
FROM node:18-alpine

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Define build arguments
ARG NODE_ENV
ARG PORT
ARG HOST
ARG LOG_LEVEL
ARG CORS_ORIGIN
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_SSL
ARG GMAIL_ADDRESS
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REFRESH_TOKEN
ARG NOTIFICATION_EMAIL

# Define environment variables
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV HOST=$HOST
ENV LOG_LEVEL=$LOG_LEVEL
ENV CORS_ORIGIN=$CORS_ORIGIN
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV DB_SSL=$DB_SSL
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV GMAIL_ADDRESS=$GMAIL_ADDRESS
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_REFRESH_TOKEN=$GOOGLE_REFRESH_TOKEN
ENV NOTIFICATION_EMAIL=$NOTIFICATION_EMAIL

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build TypeScript code
RUN npm run build

# Expose the port the app runs on
EXPOSE $PORT

# Command to run the application
CMD ["npm", "start"]